[Chore] 서브모듈로 환경변수 관리 (#10)
* chore: 서브모듈 설정

* chore: 서브모듈 최신화 및 ignore 추가

* chore: 서브모듈 설정정보 추가

* chore: 배포 파이프라인 환경변수 추가

* chore: 서브모듈 레포 ssh 사용

* feat: 테스트 환경변수 서브모듈 추가

* feat: CI 서브모듈 변경 확인

* fix: 테스트 리소스 처리 단계에 의존성 추가

* fix: test 시 main 환경변수 제외

* chore: 서브모듈 최신화

* fix: user -> member 변경

* fix: 와일드카드 import 제거

* chore: 테스트 환경변수 최신화

diff --git a/.github/workflows/cicd-dev.yml b/.github/workflows/cicd-dev.yml
--- a/.github/workflows/cicd-dev.yml
+++ b/.github/workflows/cicd-dev.yml
@@ -11,6 +11,20 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
+          ssh-known-hosts: github.com
+
+      - name: Update submodule to remote HEAD
+        run: git submodule update --remote
+
+      - name: Fail if submodule changed
+        run: |
+          if git diff --exit-code | grep -q 'Subproject'; then
+            echo "::error ::서브모듈에 변경 사항이 있습니다."
+            exit 1
+          fi
 
       - name: Set up JDK 21
         uses: actions/setup-java@v4
@@ -37,6 +51,19 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
+          ssh-known-hosts: github.com
+
+      - name: Send env configs to remote
+        uses: appleboy/scp-action@master
+        with:
+          username: ${{ secrets.DEV_USERNAME }}
+          host: ${{ secrets.DEV_HOST }}
+          key: ${{ secrets.DEV_SSH_KEY }}
+          source: "./YAPP-ENV/"
+          target: "/home/app/env"
 
       - name: Send script to remote
         uses: appleboy/scp-action@master
